baseURL = 'https://soomin81.github.io/'
locale = 'ko-kr'
title = '수민의 개발 블로그'
theme = "PaperMod"

[outputs]
home = ["HTML", "RSS", "JSON"]  # 검색 기능에 필요

[params]
defaultTheme = "auto"           # 시스템 다크/라이트 모드 따라감
ShowPostNavLinks = true         # 다음글/이전글
ShowCodeCopyButtons = true      # 코드 복사 버튼
ShowToc = true                  # 목차
TocOpen = false                 # 목차 기본 접힘
ShowBreadCrumbs = true          # 경로 표시
ShowCategories = true           # 카테고리 표시
favicon = "/favicon.ico"        # 파비콘

[params.homeInfoParams]
Title = "안녕하세요 👋"
Content = "기억은 휘발되지만 기록은 남습니다.  \n검색해도 없어서 직접 씁니다.  \n미래의 나를 위한 메모장입니다."

# 상단 메뉴
[[menus.main]]
name = "글 목록"
url = "/posts/"
weight = 1

[[menus.main]]
name = "카테고리"
url = "/categories/"
weight = 2

[[menus.main]]
name = "태그"
url = "/tags/"
weight = 3

[[menus.main]]
name = "검색"
url = "/search/"
weight = 4

